2019/12/05 23:35:08 [error] 332#332: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.3, server: _, request: "GET //get_stats/4 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.1.200", referrer: "http://192.168.1.200/"
2019/12/05 23:35:08 [error] 332#332: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.3, server: _, request: "GET //get_stats/4 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.1.200", referrer: "http://192.168.1.200/"
